package export

const UserTemplate string = `# OpenVPN Client Config for {{ .CommonName }}
# Autogenerated by {{ .Tool }}
#    on {{ .Date }}
#    should connect as {{ .IP }}
client
tls-client
dev tun
proto udp
remote {{ .Host }} {{ .Port }}
resolv-retry infinite
nobind
verb 3

passtos
route-delay 4
script-security 2

# Opionated cipher list for TLS
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384:TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
cipher AES-256-GCM
auth-nocache
# when a ECDSA key is used then "keyAgreement" flag is needed for being ECDH "capable" (as opposed to ephemeral ECDHE)
remote-cert-ku a8 a0 80 88
tls-version-min 1.2

# Verify the remote server's common name
verify-x509-name "{{ .ServerCommonName }}" name

# Inline certs, keys and tls-crypt follows
<ca>
{{ .Ca }}</ca>
<cert>
{{ .Cert }}</cert>
<key>
{{ .Key }}</key>
{{ .TlsCrypt }}
`
